# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  markdown:
    class: AppBundle\Utils\Markdown

  app.twig.app_extension:
    class:      AppBundle\Twig\AppExtension
    arguments:
      - '@markdown'
    public:     false
    tags:
      - { name: twig.extension }

  app.post_manager:
    class:      AppBundle\Utils\PostManager
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@request_stack'
      - '@session.flash_bag'

  app.post_subscriber:
    class:    AppBundle\EventListener\PostListener
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@request_stack'
      - '@session.flash_bag'